### Variables
@Host = http://localhost:5022
@ContactId = 3c6cec22-689b-42dc-9b22-83df0f740545
//00000000-0000-0000-0000-000000000000
@NoteId = 00000000-0000-0000-0000-000000000000

### 1. GET all people (Check if Adam Nowak is there)
GET {{Host}}/api/contacts?page=1&size=10
Accept: application/json

### 2. GET specific person (Replace @ContactId with one from the list above)
GET {{Host}}/api/contacts/{{ContactId}}
Accept: application/json

### 3. POST - Create a valid person
POST {{Host}}/api/contacts
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan.kowalski@wsei.edu.pl",
  "phone": "+48 500 600 700",
  "gender": 0,
  "birthDate": "1995-05-15T00:00:00Z"
}

### 4. POST - Test Validation (Should return 400 Bad Request)
POST {{Host}}/api/contacts
Content-Type: application/json

{
  "firstName": "",
  "lastName": "TooYoung",
  "email": "wrong-email-format",
  "phone": "123",
  "gender": 0,
  "birthDate": "2025-01-01T00:00:00Z"
}

### 5. PUT - Update existing person
PUT {{Host}}/api/contacts/{{ContactId}}
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak-Updated",
  "email": "adam.updated@example.com",
  "status": 2
}


### 6. POST - Add a note to a person 
POST {{Host}}/api/contacts/{{ContactId}}/notes
Content-Type: application/json

{
  "content": "This is a new test note created in Lab 5"
}

### 7. GET - Get all notes for a person 
# Use this to find the NoteId for the delete task below!
GET {{Host}}/api/contacts/{{ContactId}}/notes
Accept: application/json

### 8. POST - Test Global Exception Handler 
# Send a note to a fake ID to see the ProblemDetails response
POST {{Host}}/api/contacts/00000000-0000-0000-0000-000000000000/notes
Content-Type: application/json

{
  "content": "This should trigger ContactNotFoundException"
}

### 9. DELETE - Remove a note
# Replace NoteId at the top with a real ID from request #7
DELETE {{Host}}/api/contacts/{{ContactId}}/notes/{{NoteId}}